<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="abhichak-lap" name="GenReport" tests="4" failures="1" timestamp="7 Jul 2015 15:17:13 GMT" time="10.315" errors="0">
  <testcase name="MoneyTransfer" time="10.267" classname="ExcelResults.BankTest"/>
  <testcase name="BillPayment" time="0.048" classname="ExcelResults.BankTest">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
	at ExcelResults.BankTest.BillPayment(BankTest.java:37)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- BillPayment -->
  <testcase name="StdGen" time="0.0" classname="ExcelResults.BankTest"/>
  <testcase name="ApplyCC" time="0.0" classname="ExcelResults.BankTest">
    <skipped/>
  </testcase> <!-- ApplyCC -->
</testsuite> <!-- GenReport -->
